#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8384" \
        s6-setuidgid abc syncthing \
        -home=/config -no-browser -no-restart \
        --gui-address="0.0.0.0:8384"
